In [2]:
import sys
import numpy as np

In [3]:
# Basic Numpy Arrays
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [4]:
a = np.array([1, 2, 3, 4])

In [5]:
b = np.array([0, .5, 1, 1.5, 2])

In [6]:
a[0], a[1]

(1, 2)

In [7]:
a[0:]

array([1, 2, 3, 4])

In [8]:
a[1:3] 
# indices from 1 to 3 excluding index 3

array([2, 3])

In [9]:
a[1:-1]

array([2, 3])

In [10]:
a[::2]

array([1, 3])

In [11]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [12]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [14]:
b[[0, 2, -1]]

array([0., 1., 2.])

In [15]:
# Array Types

In [16]:
a

array([1, 2, 3, 4])

In [17]:
a.dtype

dtype('int32')

In [18]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [19]:
b.dtype

dtype('float64')

In [21]:
np.array([1, 2, 3, 4], dtype=float)

array([1., 2., 3., 4.])

In [23]:
np.array([1, 2, 3, 4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [24]:
c = np.array(['a', 'b', 'c'])

In [25]:
c.dtype

dtype('<U1')

In [26]:
d = np.array([{'a': 1}, sys])

In [27]:
d.dtype

dtype('O')

In [28]:
# Dimensions and shapes
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [30]:
A.shape
# (2 rows, 3 columns)

(2, 3)

In [40]:
A.ndim
# 2 sets of [[?

2

In [33]:
A.size
# 6 individual numbers within the array

6

In [34]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7]
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

In [35]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [37]:
B.shape
# 2 groups, 2 rows ine ach group, 3 columns in each group

(2, 2, 3)

In [39]:
B.ndim

3

In [42]:
B.size
# 12 individual numbers within the array.

12

In [44]:
C = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4]
    ]
])

c:\users\maullonv\appdata\local\programs\python\python37-32\lib\site-packages\ipykernel_launcher.py:7: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  import sys


In [45]:
C.dtype

dtype('O')

In [46]:
C.shape

(2,)

In [47]:
C.size

2

In [48]:
type(C[0])

list

In [58]:
# Indexing and Slicing of Matrices

# Square matrix
A = np.array([
#.   0. 1. 2.    
    [1, 2, 3], #0
    [4, 5, 6], #1
    [7, 8 ,9]  #2
])

In [59]:
A[1]

array([4, 5, 6])

In [60]:
A[1][0]
# row first, then column.

4

In [61]:
# A[d1, d2, d3, d4]
A[1, 0]
# basically combined the above.

4

In [62]:
A[0:2]
# All rows from 0(including 0) up to and excluding 2

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [64]:
A[:2, 2:]

array([[3],
       [6]])

In [65]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [66]:
A[2] = 99
# This updates all indices in 2 position as 99.

In [67]:
A

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [99, 99, 99]])

In [68]:
# Summary Statistics
a = np.array([1, 2, 3, 4])

In [69]:
a.sum()

10

In [70]:
a.mean()

2.5

In [71]:
a.std()

1.118033988749895

In [72]:
a.var()

1.25

In [73]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [74]:
A.sum()

45

In [75]:
A.mean()

5.0

In [76]:
A.std()

2.581988897471611

In [77]:
A.var()

6.666666666666667

In [78]:
A.sum(axis=0)
# This provides the sum of numbers within each column index.

array([12, 15, 18])

In [79]:
A.sum(axis=1)
# This provides the sum of numbers within each row index.

array([ 6, 15, 24])

In [80]:
A.mean(axis=0)
# This provides the mean/ avrg. of the numbers within each column index.
# Ex. For column 1: 1+4+7 = 12 / 3 = 4 <- which is the avrg

array([4., 5., 6.])

In [ ]:
A.mean(axis=1)
# Similar to above.
# This provides the mean/avg. of the numbers within each row index.
# Ex. For row 1: 1+2+3 = 6 / 3 = 2 

In [81]:
A.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [82]:
A.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

In [84]:
# Broadcasting and Vectorized Operations

a = np.arange(4)

In [85]:
a

array([0, 1, 2, 3])

In [86]:
a + 10

array([10, 11, 12, 13])

In [87]:
a * 10

array([ 0, 10, 20, 30])

In [88]:
a

array([0, 1, 2, 3])

In [89]:
a += 100

In [90]:
a

array([100, 101, 102, 103])

In [91]:
l = [0, 1, 2, 3]

In [92]:
[i * 10 for i in l]

[0, 10, 20, 30]

In [93]:
a = np.arange(4)

In [94]:
a

array([0, 1, 2, 3])

In [95]:
b = np.array([10, 10, 10, 10])

In [96]:
b

array([10, 10, 10, 10])

In [97]:
a + b

array([10, 11, 12, 13])

In [98]:
a * b

array([ 0, 10, 20, 30])

In [99]:
# Boolean Arrays

a = np.arange(4)

In [100]:
a

array([0, 1, 2, 3])

In [101]:
a[0], a[-1]

(0, 3)

In [102]:
a[[0, -1]]

array([0, 3])

In [103]:
a[[True, False, False, True]]

array([0, 3])

In [104]:
a

array([0, 1, 2, 3])

In [105]:
a >= 2

array([False, False,  True,  True])

In [106]:
a[a >= 2]

array([2, 3])

In [107]:
a.mean()

1.5

In [108]:
a[a > a.mean()]

array([2, 3])

In [109]:
a[~(a > a.mean())]

array([0, 1])

In [110]:
a[(a == 0) | (a == 1)]

array([0, 1])

In [111]:
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

In [112]:
A = np.random.randint(100, size=(3, 3))

In [113]:
A

array([[11, 46, 67],
       [35, 89, 64],
       [86, 41, 20]])

In [114]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([11, 67, 89, 86, 20])

In [115]:
A > 30

array([[False,  True,  True],
       [ True,  True,  True],
       [ True,  True, False]])

In [116]:
A[A > 30]

array([46, 67, 35, 89, 64, 86, 41])

In [117]:
# Linear Algebra
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [118]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [119]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [120]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [121]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [122]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [123]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])