In [2]:
import sys
import numpy as np

In [3]:
# Basic Numpy Arrays
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [4]:
a = np.array([1, 2, 3, 4])

In [5]:
b = np.array([0, .5, 1, 1.5, 2])

In [6]:
a[0], a[1]

(1, 2)

In [7]:
a[0:]
# Provides all entries from 0 index up to AND including the max index.

array([1, 2, 3, 4])

In [8]:
a[1:3] 
# Indices from 1 up to 3, excluding index 3.

array([2, 3])

In [9]:
a[1:-1]

array([2, 3])

In [10]:
a[::2]

array([1, 3])

In [11]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [12]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [14]:
b[[0, 2, -1]]

array([0., 1., 2.])

In [15]:
# Array Types

In [16]:
a

array([1, 2, 3, 4])

In [17]:
a.dtype

dtype('int32')

In [18]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [19]:
b.dtype

dtype('float64')

In [21]:
np.array([1, 2, 3, 4], dtype=float)

array([1., 2., 3., 4.])

In [23]:
np.array([1, 2, 3, 4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [24]:
c = np.array(['a', 'b', 'c'])

In [25]:
c.dtype

dtype('<U1')

In [26]:
d = np.array([{'a': 1}, sys])

In [27]:
d.dtype

dtype('O')

In [28]:
# Dimensions and shapes
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [166]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
A.shape
# (2 rows, 3 columns)

(2, 3)

In [40]:
A.ndim
# 2 sets of [[?

2

In [33]:
A.size
# 6 individual numbers within the array

6

In [34]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7]
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

In [35]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [37]:
B.shape
# 2 groups, 2 rows in each group, 3 columns in each group

(2, 2, 3)

In [39]:
B.ndim

3

In [42]:
B.size
# 12 individual numbers within the array.

12

In [ ]:
# If the shape isn't consistent, it'll just fall back to regular Python objects:

In [44]:
C = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4]
    ]
])

c:\users\maullonv\appdata\local\programs\python\python37-32\lib\site-packages\ipykernel_launcher.py:7: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  import sys


In [167]:
C

array([list([[12, 11, 10], [9, 8, 7]]), list([[6, 5, 4]])], dtype=object)

In [45]:
C.dtype

dtype('O')

In [46]:
C.shape

(2,)

In [47]:
C.size

2

In [48]:
type(C[0])
# Recall what C looks like above.

list

In [58]:
# Indexing and Slicing of Matrices

# Square matrix
A = np.array([
#.   0. 1. 2.    
    [1, 2, 3], #0
    [4, 5, 6], #1
    [7, 8 ,9]  #2
])

In [168]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
A[1]

array([4, 5, 6])

In [60]:
A[1][0]
# row first, then column.

4

In [61]:
# A[d1, d2, d3, d4]
A[1, 0]
# basically combined the above.

4

In [62]:
A[0:2]
# All rows from index 0(including 0) up to and excluding index 2.

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [64]:
A[:2, 2:]

array([[3],
       [6]])

In [65]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [66]:
A[2] = 99
# This updates all indices in 2 position as 99.

In [67]:
A

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [99, 99, 99]])

In [68]:
# Summary Statistics
a = np.array([1, 2, 3, 4])

In [69]:
a.sum()

10

In [70]:
a.mean()

2.5

In [71]:
a.std()

1.118033988749895

In [72]:
a.var()

1.25

In [73]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [74]:
A.sum()

45

In [75]:
A.mean()

5.0

In [76]:
A.std()

2.581988897471611

In [77]:
A.var()

6.666666666666667

In [78]:
A.sum(axis=0)
# This provides the sum of numbers within each column index.

array([12, 15, 18])

In [79]:
A.sum(axis=1)
# This provides the sum of numbers within each row index.

array([ 6, 15, 24])

In [80]:
A.mean(axis=0)
# This provides the mean/ avrg. of the numbers within each column index.
# Ex. For column 1: 1+4+7 = 12 / 3 = 4 <- which is the avrg.

array([4., 5., 6.])

In [169]:
A.mean(axis=1)
# Similar to above.
# This provides the mean/avg. of the numbers within each row index.
# Ex. For row 1: 1+2+3 = 6 / 3 = 2 

array([2., 5., 8.])

In [81]:
A.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [82]:
A.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

In [84]:
# Broadcasting and Vectorized Operations

a = np.arange(4)
# Creates an array consisting of 4 entries as the indices.

In [85]:
a

array([0, 1, 2, 3])

In [86]:
a + 10

array([10, 11, 12, 13])

In [87]:
a * 10

array([ 0, 10, 20, 30])

In [88]:
a

array([0, 1, 2, 3])

In [89]:
a += 100

In [90]:
a

array([100, 101, 102, 103])

In [91]:
l = [0, 1, 2, 3]

In [92]:
[i * 10 for i in l]

[0, 10, 20, 30]

In [93]:
a = np.arange(4)

In [94]:
a

array([0, 1, 2, 3])

In [95]:
b = np.array([10, 10, 10, 10])

In [96]:
b

array([10, 10, 10, 10])

In [97]:
a + b

array([10, 11, 12, 13])

In [98]:
a * b

array([ 0, 10, 20, 30])

In [99]:
# Boolean Arrays

a = np.arange(4)

In [100]:
a

array([0, 1, 2, 3])

In [101]:
a[0], a[-1]

(0, 3)

In [102]:
a[[0, -1]]

array([0, 3])

In [103]:
a[[True, False, False, True]]

array([0, 3])

In [104]:
a

array([0, 1, 2, 3])

In [105]:
a >= 2

array([False, False,  True,  True])

In [106]:
a[a >= 2]

array([2, 3])

In [107]:
a.mean()

1.5

In [108]:
a[a > a.mean()]

array([2, 3])

In [109]:
a[~(a > a.mean())]
# The '~' implies negation of the conditions within the brackets.

array([0, 1])

In [110]:
a[(a == 0) | (a == 1)]

array([0, 1])

In [111]:
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

In [112]:
A = np.random.randint(100, size=(3, 3))

In [113]:
A

array([[11, 46, 67],
       [35, 89, 64],
       [86, 41, 20]])

In [114]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([11, 67, 89, 86, 20])

In [115]:
A > 30

array([[False,  True,  True],
       [ True,  True,  True],
       [ True,  True, False]])

In [116]:
A[A > 30]

array([46, 67, 35, 89, 64, 86, 41])

In [117]:
# Linear Algebra
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [118]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [119]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [120]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [121]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [122]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [123]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

In [124]:
# Size of objects in Memory
# Int, floats

sys.getsizeof(1)

14

In [125]:
# Longs are even longer
sys.getsizeof(10**100)

58

In [126]:
np.dtype(int).itemsize

4

In [127]:
np.dtype(np.int8).itemsize

1

In [128]:
np.dtype(float).itemsize

8

In [129]:
# Lists are even larger.

# A one element list.
sys.getsizeof([1])

40

In [131]:
# An array of one element in numpy.
np.array([1]).nbytes

4

In [132]:
# Performance is also important.

l = list(range(100000))

In [133]:
a = np.arange(100000)

In [134]:
%time np.sum(a ** 2)

Wall time: 1 ms


216474736

In [135]:
%time sum([x ** 2 for x in l])

Wall time: 54 ms


333328333350000

In [136]:
# Useful Numpy Functions

# random
np.random.random(size = 2)

array([0.11315726, 0.05487451])

In [137]:
np.random.normal(size = 2)

array([-0.51091885,  1.54343796])

In [138]:
np.random.rand(2, 4)
# 2 rows, 4 columns

array([[0.98193572, 0.72405173, 0.85374448, 0.03834963],
       [0.56401802, 0.47346106, 0.72873514, 0.83903324]])

In [139]:
# arange
np.arange(10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [140]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [141]:
np.arange(0, 1, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [142]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [143]:
np.arange(10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [144]:
np.linspace(0, 1, 5)
# start at 0, stop at 1, 5 entries.

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [145]:
np.linspace(0, 1, 20)
# start at 0, stop at 1, 20 entries.

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [146]:
np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [147]:
# zeros, ones, empty
np.zeros(5)
# 5 float '0.'

array([0., 0., 0., 0., 0.])

In [150]:
np.zeros((3,3))
# 3 rows with 3 entries each where each entry is float '0.'

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [152]:
np.zeros((3, 3), dtype=int)
# 3 rows with 3 entries each, where each entry is int '0'.

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [154]:
np.ones(5)
# 1 row with 5 entries as float '1.'.

array([1., 1., 1., 1., 1.])

In [156]:
np.ones((3, 3))
# 3 rows with 3 entries each, where each entry is float '1.'.

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [157]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [158]:
np.empty((2, 2))

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

In [160]:
# identity and eye

np.identity(3)
# identity matrix with 3 rows.

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [161]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [163]:
np.eye(8, 4)
# 8 by 4 identity matrix.

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [164]:
np.eye(8, 4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [165]:
"Hello World"[6]

'W'